server:
    port: 9527

eureka:
    instance:
        hostname: 127.0.0.1
    client:
        register-with-eureka: false
        fetch-registry: false
    server:
        wait-time-in-ms-when-sync-empty: 0