server:
  port: 8080
  servlet:
    context-path: /springCloud
spring:
  application:
    name: springCloud
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/donggw
    username: donggw
    password: donggw
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  mail:
    host: smtp.qq.com
    port: 587
    username: your_email@qq.com
    password: your_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9527/eureka/

#management:
#   endpoint:
#     health:
#       show-details: always

logging:
  level:
    com.netflix.discovery: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE